server:
  port: 9999
spring:
  application:
    name: gdutDyas-admin
  datasource:
    url: jdbc:mysql://localhost:3306/gdutdays?useUnicode=true&characterEncoding=UTF-8&serverTimeZone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  redis:
    host: localhost
    port: 6379
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
